//! exit_code: 1
fn main() {
    break;  // diag: error(break_outside_of_loop): "break outside of loop"
}
