//! exit_code: 1
fn main() {
    std::const_assert_eq!(1, 2);  // diag: error(const_panic): "panic during constant evaluation at tests/diag/const_panic.alu:3:5: assertion failed (1 != 2))"
}
