//! exit_code: 1
fn main() {
    defer {
        defer {};  // diag: error(defer_in_defer): "cannot defer inside a defered expression"
    };
}
